### ISSUE TITLE
create a readme file for my portfolio project

### ISSUE THREAD

**Issue by dxfuryman** [DXFURYMAN/new-portfolio2#6]

**Comment by cjstyles6** [comment]
@dxfuryman i can work on this

**Comment by dxfuryman** [comment]
@cjstyles6 go ahead i am assigning you this one

**Comment by cjstyles6** [comment]
Ok I'll work on it soon

**Comment by cjstyles6** [comment]
@dxfuryman i'm done with it,you're gonna do some editing on it,for places like the live demo link and your email address

**Comment by dxfuryman** [comment]
@cjstyles6 go for it
